name: Cache-evict-attack

on:
  workflow_dispatch:
  push:

env:
  GO_VERSION: "1.18"

jobs:
  evict-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore go cache
        id: go-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}

      - name: random data
        run: |
          # head -c 10737418230 </dev/urandom > randomfile
# dd if=/dev/zero of=./randomfile bs=4k iflag=fullblock,count_bytes count=10737418230
# echo "aaa" >> randomfile
# fallocate -l 5G randomfile

# head -c 10737418230 </dev/urandom > randomfile

      - name: Evict cache
        id: evict-cache
        uses: actions/cache@v2
        with:
          # upload-chunk-size: 10737418240
          path: |
            randomfile
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/randomfile') }}

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name:
        run: |
          go mod tidy
          ls -lh ~/go/pkg/mod
