name: Cache-evict-attack

on:
  workflow_dispatch:

env:
  GO_VERSION: "1.18"

jobs:
  evict-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore go cache
        id: go-cache
        uses: houdini91/cache@master
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name:
        run: |
          go mod tidy
          ls -lh ~/go/pkg/mod
