name: GitHub Actions Workflow with NPM cache

on:
  workflow_dispatch:

jobs:
  evict-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore go cache
        id: go-cache
        uses: houdini91/cache@master
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}

      - name:
        run: |
          ls -lh ~/go/pkg/mod
